### ISSUE TITLE
python setup.py install error with ["ninja",  "-v"]

### ISSUE THREAD

**Issue by louislau1129** [laekov/fastmoe#111]
**Describe the bug**
Have error with ["ninja",  "-v"] in the last step [7/7] of installation.

**To Reproduce**
[USE_NCCL=1] python setup.py install

**Expected behavior**
compiled successfully

**Logs**
[7/7] /usr/local/cuda-10.2/bin/nvcc --generate-dependencies-with-compile --dependency-output /home/louislau/adaptChildSpeech/fastmoe/build/temp.linux-x86_64-3.8/cuda/parallel_linear.o.d -I/home/louislau/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/include -I/home/louislau/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/louislau/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/include/TH -I/home/louislau/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/home/louislau/anaconda3/envs/espnet/include/python3.8 -c -c /home/louislau/adaptChildSpeech/fastmoe/cuda/parallel_linear.cu -o /home/louislau/adaptChildSpeech/fastmoe/build/temp.linux-x86_64-3.8/cuda/parallel_linear.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DFMOE_USE_NCCL -DUSE_C10D_NCCL -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=fmoe_cuda -DTORCH_EXTENSION_NAME=fmoe_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/louislau/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1667, in _run_ninja_build
    subprocess.run(
  File "/home/louislau/anaconda3/envs/espnet/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

**Platform**
 - Device: NVIDIA GTX 1080 Ti
 - OS: Ubuntu 16.04.7 LTS
 - CUDA version: 10.2
 - NCCL version: 2.7.8-1
 - PyTorch version: 1.8.0

**Additional context**
Whether with USE_NCCL=1 or not, all have this error.
Whether with pytorch==1.10.1 or pytorch==1.8.0, all have this error.

Any idea on this compilation problem? Thanks in advance.

**Comment by laekov** [comment]
It seems like an error occured when compiling a module of FastMoE using NVCC, and thus not related to PyTorch. It is hard to tell the issue from the log of ninja, as nvcc's output does not present. 
Can you please find out the output of nvcc?

**Comment by louislau1129** [comment]
Both "USE_NCLL=1" or not will present the same error.
I found there is a FAILED Message before the above ninja issue, is this related? 

[2/7] c++ -MMD -MF /home/louislau/adaptChildSpeech/fastmoe/build/temp.linux-x86_64-3.8/cuda/fastermoe/smart_schedule.o.d -pthread -B /home/louislau/anaconda3/envs/espnet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/cuda-10.2/include -fPIC -I/home/louislau/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/include -I/home/louislau/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/louislau/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/include/TH -I/home/louislau/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/home/louislau/anaconda3/envs/espnet/include/python3.8 -c -c /home/louislau/adaptChildSpeech/fastmoe/cuda/fastermoe/smart_schedule.cpp -o /home/louislau/adaptChildSpeech/fastmoe/build/temp.linux-x86_64-3.8/cuda/fastermoe/smart_schedule.o -DFMOE_USE_NCCL -DUSE_C10D_NCCL -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=fmoe_cuda -DTORCH_EXTENSION_NAME=fmoe_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
**FAILED: /home/louislau/adaptChildSpeech/fastmoe/build/temp.linux-x86_64-3.8/cuda/fastermoe/smart_schedule.o** 
c++ -MMD -MF /home/louislau/adaptChildSpeech/fastmoe/build/temp.linux-x86_64-3.8/cuda/fastermoe/smart_schedule.o.d -pthread -B /home/louislau/anaconda3/envs/espnet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/cuda-10.2/include -fPIC -I/home/louislau/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/include -I/home/louislau/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/louislau/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/include/TH -I/home/louislau/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/home/louislau/anaconda3/envs/espnet/include/python3.8 -c -c /home/louislau/adaptChildSpeech/fastmoe/cuda/fastermoe/smart_schedule.cpp -o /home/louislau/adaptChildSpeech/fastmoe/build/temp.linux-x86_64-3.8/cuda/fastermoe/smart_schedule.o -DFMOE_USE_NCCL -DUSE_C10D_NCCL -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=fmoe_cuda -DTORCH_EXTENSION_NAME=fmoe_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14

**Comment by louislau1129** [comment]
Attached is the overall log:
[setup.log](https://github.com/laekov/fastmoe/files/8754347/setup.log)

**Comment by laekov** [comment]
Thanks for the log, from which I can see the key issue is

```
/home/louislau/adaptChildSpeech/fastmoe/cuda/fastermoe/smart_schedule.h:172:61: error: too few arguments to function ‘cudaError_t cudaStreamWaitEvent(cudaStream_t, cudaEvent_t, unsigned int)
’
                 cudaStreamWaitEvent(smgr->stream(1), evt_get);
 ```

You should add an additional `0` as the argument to `cudaStreamWaitEvent` for CUDA 10.2. Can you please try if that works? (And a PR for CUDA compatibility will be highly appreciated)

**Comment by louislau1129** [comment]
> add an additional `0` as the argument to `cudaStreamWaitEvent` for CUDA 10.2

Umm... Sorry that I am not familiar with CUDA, could you kindly point out how to do that in detail? e.g., find which file and modify it? Just an additional concern, will this modification affect other things which depend on cuda?

**Comment by laekov** [comment]
In `fastmoe/cuda/fastermoe/smart_schedule.h` line `172`, modify it as follow.

```
cudaStreamWaitEvent(smgr->stream(1), evt_get, 0);
```

The `0` here is a deprecated flag in newer versions of CUDA. I suppose there is no other effect.

**Comment by louislau1129** [comment]
As a quick follow-up, I have found that! It is ok, lacking the third argument, 0.

**Comment by louislau1129** [comment]
Thanks for your help, it has been installed well.

**Comment by HelloWorldLTY** [comment]
Hi, I meet this error again. I use torch 2.1.2 with cuda =12.1.1. Does this project support this version of CUDA? Thanks.

**Comment by HelloWorldLTY** [comment]
Hi, I addressed this error by using the GCC with version 10.2.0. It seems that this installation does not support GCC 12.2.0 or related version. I think it is meaningful to mention this point. Thx.

**Comment by laekov** [comment]
I am not yet able to compile pytorch with gcc 12. Maybe gcc 12 is still to new (and strict) to our current software stack.
