### ISSUE TITLE
NCCL Error at /home/xxx/fastmoe/cuda/global_exchange.cpp:127 value 5

### ISSUE THREAD

**Issue by Fragile-azalea** [laekov/fastmoe#126]
**Describe the bug**
I feel confused about its error information. I am eager to get the author's interpretation, thanks very much.
NCCL Error at /home/xxx/fastmoe/cuda/global_exchange.cpp:127 value 5

**To Reproduce**
1. USE_NCCL=1 python setup.py install
2. NCCL_DEBUG=INFO python -m torch.distributed.launch --nproc_per_node=4 --nnodes=1 --node_rank=0 --master_addr=localhost breakdown_trace.py (https://github.com/laekov/fastermoe-ae/blob/master/benchmarks/breakdown_trace.py)

**Logs**
```
Running trace ./gshard-gpt layer 0 iteration 500
gpu1:8194:8194 [0] NCCL INFO Bootstrap : Using [0]ib0:10.0.0.11<0>
gpu1:8194:8194 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
gpu1:8194:8194 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB ib0:10.0.0.11<0>
gpu1:8194:8194 [0] NCCL INFO Using network IB
NCCL version 2.7.8+cuda10.2
gpu1:8197:8197 [0] NCCL INFO Bootstrap : Using [0]ib0:10.0.0.11<0>
gpu1:8195:8195 [0] NCCL INFO Bootstrap : Using [0]ib0:10.0.0.11<0>
gpu1:8197:8197 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
gpu1:8195:8195 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
gpu1:8197:8197 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB ib0:10.0.0.11<0>
gpu1:8195:8195 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB ib0:10.0.0.11<0>
gpu1:8197:8197 [0] NCCL INFO Using network IB
gpu1:8195:8195 [0] NCCL INFO Using network IB
gpu1:8196:8196 [0] NCCL INFO Bootstrap : Using [0]ib0:10.0.0.11<0>
gpu1:8196:8196 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
gpu1:8196:8196 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB ib0:10.0.0.11<0>
gpu1:8196:8196 [0] NCCL INFO Using network IB

gpu1:8195:8195 [0] init.cc:573 NCCL WARN Duplicate GPU detected : rank 1 and rank 0 both on CUDA device 3d000

gpu1:8197:8197 [0] init.cc:573 NCCL WARN Duplicate GPU detected : rank 3 and rank 0 both on CUDA device 3d000

gpu1:8194:8194 [0] init.cc:573 NCCL WARN Duplicate GPU detected : rank 0 and rank 1 both on CUDA device 3d000

gpu1:8196:8196 [0] init.cc:573 NCCL WARN Duplicate GPU detected : rank 2 and rank 0 both on CUDA device 3d000
gpu1:8197:8197 [0] NCCL INFO init.cc:840 -> 5
gpu1:8195:8195 [0] NCCL INFO init.cc:840 -> 5
gpu1:8194:8194 [0] NCCL INFO init.cc:840 -> 5
gpu1:8196:8196 [0] NCCL INFO init.cc:840 -> 5
gpu1:8197:8197 [0] NCCL INFO init.cc:876 -> 5
gpu1:8197:8197 [0] NCCL INFO init.cc:887 -> 5
NCCL Error at /home/xxx/fastmoe/cuda/global_exchange.cpp:127 value 5
gpu1:8195:8195 [0] NCCL INFO init.cc:876 -> 5
gpu1:8194:8194 [0] NCCL INFO init.cc:876 -> 5
gpu1:8195:8195 [0] NCCL INFO init.cc:887 -> 5
gpu1:8196:8196 [0] NCCL INFO init.cc:876 -> 5
gpu1:8194:8194 [0] NCCL INFO init.cc:887 -> 5
NCCL Error at /home/xxx/fastmoe/cuda/global_exchange.cpp:127 value 5
NCCL Error at /home/xxx/fastmoe/cuda/global_exchange.cpp:127 value 5
gpu1:8196:8196 [0] NCCL INFO init.cc:887 -> 5
NCCL Error at /home/xxx/fastmoe/cuda/global_exchange.cpp:127 value 5
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 255) local_rank: 0 (pid: 8194) of binary: /home/xxx/miniconda3/envs/fastmoe/bin/python
Traceback (most recent call last):
  File "/home/xxx/miniconda3/envs/fastmoe/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xxx/miniconda3/envs/fastmoe/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xxx/miniconda3/envs/fastmoe/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/xxx/miniconda3/envs/fastmoe/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/xxx/miniconda3/envs/fastmoe/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/xxx/miniconda3/envs/fastmoe/lib/python3.8/site-packages/torch/distributed/run.py", line 689, in run
    elastic_launch(
  File "/home/xxx/miniconda3/envs/fastmoe/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/xxx/miniconda3/envs/fastmoe/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 244, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
*****************************************
        breakdown_trace.py FAILED
=========================================
Root Cause:
[0]:
  time: 2022-07-21_14:34:31
  rank: 0 (local_rank: 0)
  exitcode: 255 (pid: 8194)
  error_file: <N/A>
  msg: "Process failed with exitcode 255"
=========================================
Other Failures:
[1]:
  time: 2022-07-21_14:34:31
  rank: 1 (local_rank: 1)
  exitcode: 255 (pid: 8195)
  error_file: <N/A>
  msg: "Process failed with exitcode 255"
[2]:
  time: 2022-07-21_14:34:31
  rank: 2 (local_rank: 2)
  exitcode: 255 (pid: 8196)
  error_file: <N/A>
  msg: "Process failed with exitcode 255"
[3]:
  time: 2022-07-21_14:34:31
  rank: 3 (local_rank: 3)
  exitcode: 255 (pid: 8197)
  error_file: <N/A>
  msg: "Process failed with exitcode 255"
*****************************************
```

**Platform**
- Device: GeForce RTX 2080Ti * 4
- OS: Linux gpu9 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- CUDA version: 10.2
- NCCL version: 2.7.8-1
- PyTorch version: 1.9.1
- Python Version: 3.8

**Comment by laekov** [comment]
I noticed that you have the warning in your log saying that you have multiple processes binded on the same GPU. I previously got NCCL error 5 because of that. Maybe you can try binding the processes to CUDA devices manually.

By the way, I experienced a lot of issues related to PyTorch's distributed launcher. I personally recommend MPI or SLURM to launch multiple processes. And the expert selection dataset is for 16 experts on 16 GPUs. So, I am not sure if it works correctly on 4 GPUs. Please let me know if you have any further progress or problem.
