### ISSUE TITLE
About Megatron (AttributeError: module 'fmoe_cuda' has no attribute 'ensure_nccl')

### ISSUE THREAD

**Issue by Hanlard** [laekov/fastmoe#44]
## **Describe the bug**
Error when training Megatron with switch gate.

[AttributeError: module 'fmoe_cuda' has no attribute 'ensure_nccl']

########## ERROR ##########
...
File "/opt/conda/lib/python3.8/site-packages/fastmoe-0.2.0-py3.8-linux-x86_64.egg/fmoe/functions.py", line 32, in count_by_gate
_ensure_nccl(gate)
File "/opt/conda/lib/python3.8/site-packages/fastmoe-0.2.0-py3.8-linux-x86_64.egg/fmoe/functions.py", line 16, in _ensure_nccl
fmoe_cuda.ensure_nccl(comm, t)
AttributeError: module 'fmoe_cuda' has no attribute 'ensure_nccl'
Traceback (most recent call last):
...
##  **Platform**
 - Device: [NVIDIA V100] * 2
 - Docker: [nvcr.io/nvidia/pytorch:20.12-py3]
 - Version: Megatron V2.2
 
## **MOE Arguments **   

def _add_fmoe_args(parser):

    group = parser.add_argument_group(title='fmoe')
    group.add_argument('--num-experts', type=int, default=2,  help='Num of experts')
    group.add_argument('--top-k', type=int, default=1, help='top-k experts')
    group.add_argument('--balance-strategy', default="switch", 
                       choices=['naive', 'noisy','gshard','switch'], 
                       help='Balance strategy for experts')    
    return parser

**Comment by Hanlard** [comment]
all log


using world size: 2, data-parallel-size: 2, tensor-model-parallel size: 1, pipeline-model-parallel size: 1
using torch.float16 for parameters ...
WARNING: overriding default arguments for tokenizer_type:GPT2BPETokenizer with tokenizer_type:JIEBATokenizer
------------------------ arguments ------------------------
adam_beta1 ...................................... 0.9
adam_beta2 ...................................... 0.999
adam_eps ........................................ 1e-08
adlr_autoresume ................................. False
adlr_autoresume_interval ........................ 1000
apply_query_key_layer_scaling ................... True
apply_residual_connection_post_layernorm ........ False
attention_dropout ............................... 0.1
attention_softmax_in_fp32 ....................... False
balance_strategy ................................ switch
bert_load ....................................... None
bias_dropout_fusion ............................. True
bias_gelu_fusion ................................ True
block_data_path ................................. None
checkpoint_activations .......................... False
checkpoint_num_layers ........................... 1
clip_grad ....................................... 1.0
consumed_train_samples .......................... 0
consumed_valid_samples .......................... 0
data_impl ....................................... mmap
data_parallel_size .............................. 2
data_path ....................................... ['/userhome/gpt3_data_train/cpm_ReTrain_addBaiKe_100G/Data_Processed_text_document']
DDP_impl ........................................ local
distribute_checkpointed_activations ............. False
distributed_backend ............................. nccl
eod_mask_loss ................................... False
eval_interval ................................... 1000
eval_iters ...................................... 10
exit_duration_in_mins ........................... None
exit_interval ................................... None
faiss_use_gpu ................................... False
finetune ........................................ False
fp16 ............................................ True
fp16_lm_cross_entropy ........................... False
fp32_allreduce .................................. False
fp32_residual_connection ........................ False
global_batch_size ............................... 16
hidden_dropout .................................. 0.1
hidden_size ..................................... 768
hysteresis ...................................... 2
ict_head_size ................................... None
ict_load ........................................ None
indexer_batch_size .............................. 128
indexer_log_interval ............................ 1000
init_method_std ................................. 0.02
initial_loss_scale .............................. 4294967296
layernorm_epsilon ............................... 1e-05
lazy_mpu_init ................................... None
load ............................................ checkpoints/gpt_108M_testCB2
local_rank ...................................... 0
log_interval .................................... 10
loss_scale ...................................... None
loss_scale_window ............................... 1000
lr .............................................. 0.00015
lr_decay_iters .................................. 102400
lr_decay_samples ................................ None
lr_decay_style .................................. cosine
lr_warmup_fraction .............................. 0.01
lr_warmup_iters ................................. 0
lr_warmup_samples ............................... 0
make_vocab_size_divisible_by .................... 128
mask_prob ....................................... 0.15
max_position_embeddings ......................... 1024
merge_file ...................................... bpe_3w_new/chinese_vocab.model
micro_batch_size ................................ 4
min_loss_scale .................................. 1.0
min_lr .......................................... 1e-05
mmap_warmup ..................................... False
no_load_optim ................................... False
no_load_rng ..................................... False
no_save_optim ................................... False
no_save_rng ..................................... False
num_attention_heads ............................. 12
num_experts ..................................... 2
num_layers ...................................... 12
num_workers ..................................... 2
onnx_safe ....................................... None
openai_gelu ..................................... False
override_lr_scheduler ........................... False
params_dtype .................................... torch.float16
pipeline_model_parallel_size .................... 1
query_in_block_prob ............................. 0.1
rampup_batch_size ............................... None
rank ............................................ 0
report_topk_accuracies .......................... []
reset_attention_mask ............................ False
reset_position_ids .............................. False
save ............................................ checkpoints/gpt_108M_testCB2
save_interval ................................... 10000
scaled_masked_softmax_fusion .................... True
scaled_upper_triang_masked_softmax_fusion ....... True
seed ............................................ 1234
seq_length ...................................... 1024
short_seq_prob .................................. 0.1
split ........................................... 950,49,1
tensor_model_parallel_size ...................... 1
tensorboard_dir ................................. None
titles_data_path ................................ None
tokenizer_type .................................. JIEBATokenizer
top_k ........................................... 1
train_iters ..................................... 160000
train_samples ................................... None
use_checkpoint_lr_scheduler ..................... False
use_cpu_initialization .......................... False
use_one_sent_docs ............................... False
vocab_file ...................................... bpe_3w_new/vocab.json
weight_decay .................................... 0.01
world_size ...................................... 2
-------------------- end of arguments ---------------------
setting number of micro-batches to constant 2
> building JIEBATokenizer tokenizer ...
> padded vocab (size: 30001) with 79 dummy tokens (new size: 30080)
> initializing torch distributed ...
> initializing tensor model parallel with size 1
> initializing pipeline model parallel with size 1
> setting random seeds to 1234 ...
> initializing model parallel cuda seeds on global rank 0, model parallel rank 0, and data parallel rank 0 with model parallel seed: 3952 and data parallel seed: 1234
time to initialize megatron (seconds): -52.993
[after megatron is initialized] datetime: 2021-06-08 09:47:55
building GPT model ...
> number of parameters on (tensor, pipeline) model parallel rank (0, 0): 165649968
> learning rate decay style: cosine
WARNING: could not find the metadata file checkpoints/gpt_108M_testCB2/latest_checkpointed_iteration.txt
will not load any checkpoints and will start from random
WARNING: could not find the metadata file checkpoints/gpt_108M_testCB2/latest_checkpointed_iteration.txt
will not load any checkpoints and will start from random
time (ms) | load checkpoint: 0.21
[after model, optimizer, and learning rate scheduler are built] datetime: 2021-06-08 09:47:57
> building train, validation, and test datasets ...
> datasets target sizes (minimum size):
train: 2560000
validation: 25760
test: 160
> building train, validation, and test datasets for GPT ...
> building dataset index ...
reading sizes...
reading pointers...
reading document index...
creating numpy buffer of mmap...
creating memory view of numpy buffer...
> finished creating indexed dataset in 0.003235 seconds
number of documents: 106807670
> dataset split:
train:
document indices in [0, 101467286) total of 101467286 documents
validation:
document indices in [101467286, 106700862) total of 5233576 documents
test:
document indices in [106700862, 106807670) total of 106808 documents
> loading doc-idx mapping from /userhome/gpt3_data_train/cpm_ReTrain_addBaiKe_100G/Data_Processed_text_document_train_indexmap_2560000ns_1024sl_1234s_doc_idx.npy
> loading sample-idx mapping from /userhome/gpt3_data_train/cpm_ReTrain_addBaiKe_100G/Data_Processed_text_document_train_indexmap_2560000ns_1024sl_1234s_sample_idx.npy
> loading shuffle-idx mapping from /userhome/gpt3_data_train/cpm_ReTrain_addBaiKe_100G/Data_Processed_text_document_train_indexmap_2560000ns_1024sl_1234s_shuffle_idx.npy
loaded indexed file in 0.044 seconds
total number of samples: 28897132
total number of epochs: 1
> loading doc-idx mapping from /userhome/gpt3_data_train/cpm_ReTrain_addBaiKe_100G/Data_Processed_text_document_valid_indexmap_25760ns_1024sl_1234s_doc_idx.npy
> loading sample-idx mapping from /userhome/gpt3_data_train/cpm_ReTrain_addBaiKe_100G/Data_Processed_text_document_valid_indexmap_25760ns_1024sl_1234s_sample_idx.npy
> loading shuffle-idx mapping from /userhome/gpt3_data_train/cpm_ReTrain_addBaiKe_100G/Data_Processed_text_document_valid_indexmap_25760ns_1024sl_1234s_shuffle_idx.npy
loaded indexed file in 0.008 seconds
total number of samples: 1586416
total number of epochs: 1
> loading doc-idx mapping from /userhome/gpt3_data_train/cpm_ReTrain_addBaiKe_100G/Data_Processed_text_document_test_indexmap_160ns_1024sl_1234s_doc_idx.npy
> loading sample-idx mapping from /userhome/gpt3_data_train/cpm_ReTrain_addBaiKe_100G/Data_Processed_text_document_test_indexmap_160ns_1024sl_1234s_sample_idx.npy
> loading shuffle-idx mapping from /userhome/gpt3_data_train/cpm_ReTrain_addBaiKe_100G/Data_Processed_text_document_test_indexmap_160ns_1024sl_1234s_shuffle_idx.npy
loaded indexed file in 0.002 seconds
total number of samples: 50289
total number of epochs: 1
> finished creating GPT datasets ...
[after dataloaders are built] datetime: 2021-06-08 09:47:58
done with setups ...
training ...
time (ms) | model and optimizer: 2062.95 | train/valid/test data iterators: 1758.68
[before the start of training step] datetime: 2021-06-08 09:47:58
Traceback (most recent call last):
File "pretrain_gpt.py", line 146, in <module>
pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
File "/userhome/megatron/megatron_moe/megatron/training.py", line 132, in pretrain
iteration = train(forward_step_func,
File "/userhome/megatron/megatron_moe/megatron/training.py", line 812, in train
loss_dict, skipped_iter = train_step(forward_step_func,
File "/userhome/megatron/megatron_moe/megatron/training.py", line 601, in train_step
losses_reduced = forward_backward_no_pipelining(
File "/userhome/megatron/megatron_moe/megatron/training.py", line 515, in forward_backward_no_pipelining
loss, loss_reduced = forward_step_func(data_iterator, model, input_tensor=None)
File "pretrain_gpt.py", line 102, in forward_step
output_tensor = model(tokens, position_ids, attention_mask,
File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
result = self.forward(*input, **kwargs)
File "/opt/conda/lib/python3.8/site-packages/fastmoe-0.2.0-py3.8-linux-x86_64.egg/fmoe/distributed.py", line 116, in forward
return self.module(*args, **kwargs)
File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
result = self.forward(*input, **kwargs)
File "/userhome/megatron/megatron_moe/megatron/model/module.py", line 140, in forward
outputs = self.module(*inputs, **kwargs)
File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
result = self.forward(*input, **kwargs)
File "/userhome/megatron/megatron_moe/megatron/model/gpt_model.py", line 143, in forward
return super(GPTModel, self).forward(
File "/userhome/megatron/megatron_moe/megatron/model/gpt_model.py", line 95, in forward
lm_output = self.language_model(*args, **kwargs)
File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
result = self.forward(*input, **kwargs)
File "/userhome/megatron/megatron_moe/megatron/model/language_model.py", line 414, in forward
return super(TransformerLanguageModel, self).forward(
File "/userhome/megatron/megatron_moe/megatron/model/language_model.py", line 328, in forward
transformer_output = self.transformer(transformer_input,
File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
result = self.forward(*input, **kwargs)
File "/userhome/megatron/megatron_moe/megatron/model/transformer.py", line 589, in forward
hidden_states = layer(hidden_states,
File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
result = self.forward(*input, **kwargs)
File "/userhome/megatron/megatron_moe/megatron/model/transformer.py", line 474, in forward
mlp_output, mlp_bias = self.mlp(layernorm_output)
File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
result = self.forward(*input, **kwargs)
File "/opt/conda/lib/python3.8/site-packages/fastmoe-0.2.0-py3.8-linux-x86_64.egg/fmoe/megatron/layers.py", line 140, in forward
super().forward(inp),
File "/opt/conda/lib/python3.8/site-packages/fastmoe-0.2.0-py3.8-linux-x86_64.egg/fmoe/transformer.py", line 78, in forward
output = super().forward(inp)
File "/opt/conda/lib/python3.8/site-packages/fastmoe-0.2.0-py3.8-linux-x86_64.egg/fmoe/layers.py", line 205, in forward
gate_top_k_idx, gate_score = self.gate(inp)
File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
result = self.forward(*input, **kwargs)
File "/opt/conda/lib/python3.8/site-packages/fastmoe-0.2.0-py3.8-linux-x86_64.egg/fmoe/gates/switch_gate.py", line 46, in forward
_new_lec, _new_gec, top1_idx = limit_by_capacity(
File "/opt/conda/lib/python3.8/site-packages/fastmoe-0.2.0-py3.8-linux-x86_64.egg/fmoe/gates/utils.py", line 14, in limit_by_capacity
pos, lec, gec = count_by_gate(topk_idx, num_expert, world_size,
File "/opt/conda/lib/python3.8/site-packages/fastmoe-0.2.0-py3.8-linux-x86_64.egg/fmoe/functions.py", line 32, in count_by_gate
_ensure_nccl(gate)
File "/opt/conda/lib/python3.8/site-packages/fastmoe-0.2.0-py3.8-linux-x86_64.egg/fmoe/functions.py", line 16, in _ensure_nccl
fmoe_cuda.ensure_nccl(comm, t)
AttributeError: module 'fmoe_cuda' has no attribute 'ensure_nccl'
Traceback (most recent call last):
File "pretrain_gpt.py", line 146, in <module>
pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
File "/userhome/megatron/megatron_moe/megatron/training.py", line 132, in pretrain
iteration = train(forward_step_func,
File "/userhome/megatron/megatron_moe/megatron/training.py", line 812, in train
loss_dict, skipped_iter = train_step(forward_step_func,
File "/userhome/megatron/megatron_moe/megatron/training.py", line 601, in train_step
losses_reduced = forward_backward_no_pipelining(
File "/userhome/megatron/megatron_moe/megatron/training.py", line 515, in forward_backward_no_pipelining
loss, loss_reduced = forward_step_func(data_iterator, model, input_tensor=None)
File "pretrain_gpt.py", line 102, in forward_step
output_tensor = model(tokens, position_ids, attention_mask,
File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
result = self.forward(*input, **kwargs)
File "/opt/conda/lib/python3.8/site-packages/fastmoe-0.2.0-py3.8-linux-x86_64.egg/fmoe/distributed.py", line 116, in forward
return self.module(*args, **kwargs)
File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
result = self.forward(*input, **kwargs)
File "/userhome/megatron/megatron_moe/megatron/model/module.py", line 140, in forward
outputs = self.module(*inputs, **kwargs)
File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
result = self.forward(*input, **kwargs)
File "/userhome/megatron/megatron_moe/megatron/model/gpt_model.py", line 143, in forward
return super(GPTModel, self).forward(
File "/userhome/megatron/megatron_moe/megatron/model/gpt_model.py", line 95, in forward
lm_output = self.language_model(*args, **kwargs)
File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
result = self.forward(*input, **kwargs)
File "/userhome/megatron/megatron_moe/megatron/model/language_model.py", line 414, in forward
return super(TransformerLanguageModel, self).forward(
File "/userhome/megatron/megatron_moe/megatron/model/language_model.py", line 328, in forward
transformer_output = self.transformer(transformer_input,
File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
result = self.forward(*input, **kwargs)
File "/userhome/megatron/megatron_moe/megatron/model/transformer.py", line 589, in forward
hidden_states = layer(hidden_states,
File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
result = self.forward(*input, **kwargs)
File "/userhome/megatron/megatron_moe/megatron/model/transformer.py", line 474, in forward
mlp_output, mlp_bias = self.mlp(layernorm_output)
File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
result = self.forward(*input, **kwargs)
File "/opt/conda/lib/python3.8/site-packages/fastmoe-0.2.0-py3.8-linux-x86_64.egg/fmoe/megatron/layers.py", line 140, in forward
super().forward(inp),
File "/opt/conda/lib/python3.8/site-packages/fastmoe-0.2.0-py3.8-linux-x86_64.egg/fmoe/transformer.py", line 78, in forward
output = super().forward(inp)
File "/opt/conda/lib/python3.8/site-packages/fastmoe-0.2.0-py3.8-linux-x86_64.egg/fmoe/layers.py", line 205, in forward
gate_top_k_idx, gate_score = self.gate(inp)
File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
result = self.forward(*input, **kwargs)
File "/opt/conda/lib/python3.8/site-packages/fastmoe-0.2.0-py3.8-linux-x86_64.egg/fmoe/gates/switch_gate.py", line 46, in forward
_new_lec, _new_gec, top1_idx = limit_by_capacity(
File "/opt/conda/lib/python3.8/site-packages/fastmoe-0.2.0-py3.8-linux-x86_64.egg/fmoe/gates/utils.py", line 14, in limit_by_capacity
pos, lec, gec = count_by_gate(topk_idx, num_expert, world_size,
File "/opt/conda/lib/python3.8/site-packages/fastmoe-0.2.0-py3.8-linux-x86_64.egg/fmoe/functions.py", line 32, in count_by_gate
_ensure_nccl(gate)
File "/opt/conda/lib/python3.8/site-packages/fastmoe-0.2.0-py3.8-linux-x86_64.egg/fmoe/functions.py", line 16, in _ensure_nccl
fmoe_cuda.ensure_nccl(comm, t)
AttributeError: module 'fmoe_cuda' has no attribute 'ensure_nccl'
Traceback (most recent call last):
File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 303, in <module>
main()
File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 294, in main
raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'pretrain_gpt.py', '--local_rank=1', '--tensor-model-parallel-size', '1', '--pipeline-model-parallel-size', '1', '--num-layers', '12', '--hidden-size', '768', '--num-attention-heads', '12', '--micro-batch-size', '4', '--global-batch-size', '16', '--seq-length', '1024', '--max-position-embeddings', '1024', '--train-iters', '160000', '--lr-decay-iters', '102400', '--save', 'checkpoints/gpt_108M_testCB2', '--load', 'checkpoints/gpt_108M_testCB2', '--data-path', '/userhome/gpt3_data_train/cpm_ReTrain_addBaiKe_100G/Data_Processed_text_document', '--vocab-file', 'bpe_3w_new/vocab.json', '--merge-file', 'bpe_3w_new/chinese_vocab.model', '--data-impl', 'mmap', '--split', '950,49,1', '--distributed-backend', 'nccl', '--lr', '0.00015', '--lr-decay-style', 'cosine', '--min-lr', '1.0e-5', '--weight-decay', '1e-2', '--clip-grad', '1.0', '--lr-warmup-fraction', '.01', '--log-interval', '10', '--save-interval', '10000', '--eval-interval', '1000', '--eval-iters', '10', '--fp16']' returned non-zero exit status 1.

**Comment by xptree** [comment]
Did you install fastmoe with `USE_NCCL=1` flag? I.e.,

```
USE_NCCL=1 python setup.py install
```

**Comment by Hanlard** [comment]
> Did you install fastmoe with `USE_NCCL=1` flag? I.e.,
> 
> ```
> USE_NCCL=1 python setup.py install
> ```I tried USE_NCCL=1 and the problem solved, thanks!
