### ISSUE TITLE
Error occurs when I run gpt in megtran

### ISSUE THREAD

**Issue by youth123** [laekov/fastmoe#46]
**Describe the bug**
When I have modified the megatron v2.2 according to the fmoefy-v2.2.patch  and pretrained the gpt,  the error occurs as below.

########## ERROR ##########
building GPT model ...
Traceback (most recent call last):
  File "pretrain_gpt.py", line 148, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
  File "/home/liji09/moe_demo/megatron_moe/Megatron-LM/megatron/training.py", line 116, in pretrain
    model, optimizer, lr_scheduler = setup_model_and_optimizer(model_provider)
  File "/home/liji09/moe_demo/megatron_moe/Megatron-LM/megatron/training.py", line 276, in setup_model_and_optimizer
    model = get_model(model_provider_func)
  File "/home/liji09/moe_demo/megatron_moe/Megatron-LM/megatron/training.py", line 192, in get_model
    model = model_provider_func()
  File "pretrain_gpt.py", line 52, in model_provider
    model = fmoefy(model, num_experts=4)
  File "/opt/conda/lib/python3.8/site-packages/fastmoe-0.2.0-py3.8-linux-x86_64.egg/fmoe/megatron/layers.py", line 191, in fmoefy
    l.mlp = MegatronMLP(args, mpu.get_model_parallel_group(), idx)
  File "/opt/conda/lib/python3.8/site-packages/fastmoe-0.2.0-py3.8-linux-x86_64.egg/fmoe/megatron/layers.py", line 105, in __init__
    super().__init__(
  File "/opt/conda/lib/python3.8/site-packages/fastmoe-0.2.0-py3.8-linux-x86_64.egg/fmoe/transformer.py", line 66, in __init__
    self.experts = _Expert(
  File "/opt/conda/lib/python3.8/site-packages/fastmoe-0.2.0-py3.8-linux-x86_64.egg/fmoe/transformer.py", line 18, in __init__
    self.htoh4 = FMoELinear(num_expert, d_model, d_hidden, bias=True, rank=rank)
  File "/opt/conda/lib/python3.8/site-packages/fastmoe-0.2.0-py3.8-linux-x86_64.egg/fmoe/layers.py", line 34, in __init__
    self.weight = nn.Parameter(torch.Tensor(num_expert, out_feat, in_feat))
TypeError: new(): argument 'size' must be tuple of ints, but found element of type NoneType at pos 2
./examples/pretrain_gpt.sh: line 43: --fmoefy: command not found
########### ERROR ##########

**Platform**
 - Device: Tesla v100
 - OS: Ubuntu 
 - CUDA version: 11.1
- NCCL version: 2.8.3

**Comment by laekov** [comment]
You should either add `parser = _add_fmoe_args(parser)` in Megatron's `megatron/arguments.py` or specify `hidden_hidden_size` at the place where you call `fmoefy`.

**Comment by youth123** [comment]
Thanks, adding hidden_hidden_size works. But I run across another problem. When I run in single gpu, the program looks hanging.
