### ISSUE TITLE
setup.py failed

### ISSUE THREAD

**Issue by BDHU** [laekov/fastmoe#93]
**Describe the bug**
I'm using the docker image suggested in the [Megatron-LM](https://github.com/NVIDIA/Megatron-LM/tree/main) repo. I pulled the container using `docker pull nvcr.io/nvidia/pytorch:20.12-py3`. Inside the container, I tried to clone this repo and build fastMoE, which failed.

**To Reproduce**
1. launch the container using `docker run --gpus all -it --rm --ipc=host -v /home/me/:/home/me/ --name pytorch-moe <image_ID>`
2. Once inside the container. Clone this repo and execute `USE_NCCL=1 python setup.py install`
3. It fails to build global_exchange.o

**Error Message**
Here is a complete message dump:

```text
running install
running bdist_egg
running egg_info
creating fastmoe.egg-info
writing fastmoe.egg-info/PKG-INFO
writing dependency_links to fastmoe.egg-info/dependency_links.txt
writing top-level names to fastmoe.egg-info/top_level.txt
writing manifest file 'fastmoe.egg-info/SOURCES.txt'
reading manifest file 'fastmoe.egg-info/SOURCES.txt'
writing manifest file 'fastmoe.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.8
creating build/lib.linux-x86_64-3.8/fmoe
copying fmoe/functions.py -> build/lib.linux-x86_64-3.8/fmoe
copying fmoe/layers.py -> build/lib.linux-x86_64-3.8/fmoe
copying fmoe/transformer.py -> build/lib.linux-x86_64-3.8/fmoe
copying fmoe/balance.py -> build/lib.linux-x86_64-3.8/fmoe
copying fmoe/utils.py -> build/lib.linux-x86_64-3.8/fmoe
copying fmoe/__init__.py -> build/lib.linux-x86_64-3.8/fmoe
copying fmoe/linear.py -> build/lib.linux-x86_64-3.8/fmoe
copying fmoe/distributed.py -> build/lib.linux-x86_64-3.8/fmoe
creating build/lib.linux-x86_64-3.8/fmoe/megatron
copying fmoe/megatron/layers.py -> build/lib.linux-x86_64-3.8/fmoe/megatron
copying fmoe/megatron/checkpoint.py -> build/lib.linux-x86_64-3.8/fmoe/megatron
copying fmoe/megatron/balance.py -> build/lib.linux-x86_64-3.8/fmoe/megatron
copying fmoe/megatron/utils.py -> build/lib.linux-x86_64-3.8/fmoe/megatron
copying fmoe/megatron/patch.py -> build/lib.linux-x86_64-3.8/fmoe/megatron
copying fmoe/megatron/__init__.py -> build/lib.linux-x86_64-3.8/fmoe/megatron
copying fmoe/megatron/distributed.py -> build/lib.linux-x86_64-3.8/fmoe/megatron
creating build/lib.linux-x86_64-3.8/fmoe/gates
copying fmoe/gates/naive_gate.py -> builde.g. 1.8.0/lib.linux-x86_64-3.8/fmoe/gates
copying fmoe/gates/base_gate.py -> build/lib.linux-x86_64-3.8/fmoe/gates
copying fmoe/gates/zero_gate.py -> build/lib.linux-x86_64-3.8/fmoe/gates
copying fmoe/gates/switch_gate.py -> build/lib.linux-x86_64-3.8/fmoe/gates
copying fmoe/gates/noisy_gate.py -> build/lib.linux-x86_64-3.8/fmoe/gates
copying fmoe/gates/gshard_gate.py -> build/lib.linux-x86_64-3.8/fmoe/gates
copying fmoe/gates/swipe_gate.py -> build/lib.linux-x86_64-3.8/fmoe/gates
copying fmoe/gates/utils.py -> build/lib.linux-x86_64-3.8/fmoe/gates
copying fmoe/gates/__init__.py -> build/lib.linux-x86_64-3.8/fmoe/gates
running build_ext
building 'fmoe_cuda' extension
creating /home/edwardhu/fastmoe/build/temp.linux-x86_64-3.8
creating /home/edwardhu/fastmoe/build/temp.linux-x86_64-3.8/cuda
Emitting ninja build file /home/edwardhu/fastmoe/build/temp.linux-x86_64-3.8/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/6] c++ -MMD -MF /home/edwardhu/fastmoe/build/temp.linux-x86_64-3.8/cuda/stream_manager.o.d -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/conda/lib/python3.8/site-packages/torch/include -I/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.8/site-packages/torch/include/TH -I/opt/conda/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/include/python3.8 -c -c /home/edwardhu/fastmoe/cuda/stream_manager.cpp -o /home/edwardhu/fastmoe/build/temp.linux-x86_64-3.8/cuda/stream_manager.o -DFMOE_USE_NCCL -DUSE_C10D_NCCL -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=fmoe_cuda -DTORCH_EXTENSION_NAME=fmoe_cuda -D_GLIBCXX_USE_CXX11_ABI=1 -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
[2/6] c++ -MMD -MF /home/edwardhu/fastmoe/build/temp.linux-x86_64-3.8/cuda/global_exchange.o.d -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/conda/lib/python3.8/site-packages/torch/include -I/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.8/site-packages/torch/include/TH -I/opt/conda/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/include/python3.8 -c -c /home/edwardhu/fastmoe/cuda/global_exchange.cpp -o /home/edwardhu/fastmoe/build/temp.linux-x86_64-3.8/cuda/global_exchange.o -DFMOE_USE_NCCL -DUSE_C10D_NCCL -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=fmoe_cuda -DTORCH_EXTENSION_NAME=fmoe_cuda -D_GLIBCXX_USE_CXX11_ABI=1 -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
FAILED: /home/edwardhu/fastmoe/build/temp.linux-x86_64-3.8/cuda/global_exchange.o 
c++ -MMD -MF /home/edwardhu/fastmoe/build/temp.linux-x86_64-3.8/cuda/global_exchange.o.d -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/conda/lib/python3.8/site-packages/torch/include -I/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.8/site-packages/torch/include/TH -I/opt/conda/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/include/python3.8 -c -c /home/edwardhu/fastmoe/cuda/global_exchange.cpp -o /home/edwardhu/fastmoe/build/temp.linux-x86_64-3.8/cuda/global_exchange.o -DFMOE_USE_NCCL -DUSE_C10D_NCCL -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=fmoe_cuda -DTORCH_EXTENSION_NAME=fmoe_cuda -D_GLIBCXX_USE_CXX11_ABI=1 -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /opt/conda/lib/python3.8/site-packages/torch/include/ATen/Parallel.h:149,
                 from /opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                 from /opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                 from /opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                 from /opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:12,
                 from /opt/conda/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                 from /home/edwardhu/fastmoe/cuda/global_exchange.cpp:3:
/opt/conda/lib/python3.8/site-packages/torch/include/ATen/ParallelOpenMP.h:84: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
   84 | #pragma omp parallel for if ((end - begin) >= grain_size)
      | 
/home/edwardhu/fastmoe/cuda/global_exchange.cpp: In member function ‘ncclComm* HackNCCLGroup::getcomm(c10::Device)’:
/home/edwardhu/fastmoe/cuda/global_exchange.cpp:118:38: error: no matching function for call to ‘HackNCCLGroup::broadcastUniqueNCCLID(ncclUniqueId*)’
  118 |         broadcastUniqueNCCLID(&ncclID);
      |                                      ^
In file included from /home/edwardhu/fastmoe/cuda/global_exchange.cpp:101:
/opt/conda/lib/python3.8/site-packages/torch/include/c10d/ProcessGroupNCCL.hpp:509:8: note: candidate: ‘void c10d::ProcessGroupNCCL::broadcastUniqueNCCLID(ncclUniqueId*, c10d::OpType, const string&, int)’
  509 |   void broadcastUniqueNCCLID(
      |        ^~~~~~~~~~~~~~~~~~~~~e.g. 1.8.0
/opt/conda/lib/python3.8/site-packages/torch/include/c10d/ProcessGroupNCCL.hpp:509:8: note:   candidate expects 4 arguments, 1 provided
[3/6] c++ -MMD -MF /home/edwardhu/fastmoe/build/temp.linux-x86_64-3.8/cuda/fmoe_cuda.o.d -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/conda/lib/python3.8/site-packages/torch/include -I/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.8/site-packages/torch/include/TH -I/opt/conda/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/include/python3.8 -c -c /home/edwardhu/fastmoe/cuda/fmoe_cuda.cpp -o /home/edwardhu/fastmoe/build/temp.linux-x86_64-3.8/cuda/fmoe_cuda.o -DFMOE_USE_NCCL -DUSE_C10D_NCCL -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=fmoe_cuda -DTORCH_EXTENSION_NAME=fmoe_cuda -D_GLIBCXX_USE_CXX11_ABI=1 -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /opt/conda/lib/python3.8/site-packages/torch/include/ATen/Parallel.h:149,
                 from /opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                 from /opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                 from /opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                 from /opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:12,
                 from /opt/conda/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                 from /home/edwardhu/fastmoe/cuda/fmoe_cuda.cpp:3:
/opt/conda/lib/python3.8/site-packages/torch/include/ATen/ParallelOpenMP.h:84: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
   84 | #pragma omp parallel for if ((end - begin) >= grain_size)
      | 
[4/6] /usr/local/cuda/bin/nvcc -I/opt/conda/lib/python3.8/site-packages/torch/include -I/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.8/site-packages/torch/include/TH -I/opt/conda/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/include/python3.8 -c -c /home/edwardhu/fastmoe/cuda/parallel_linear.cu -o /home/edwardhu/fastmoe/build/temp.linux-x86_64-3.8/cuda/parallel_linear.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DFMOE_USE_NCCL -DUSE_C10D_NCCL -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=fmoe_cuda -DTORCH_EXTENSION_NAME=fmoe_cuda -D_GLIBCXX_USE_CXX11_ABI=1 -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_52,code=sm_52 -gencode=arch=compute_86,code=sm_86 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_75,code=sm_75
[5/6] /usr/local/cuda/bin/nvcc -I/opt/conda/lib/python3.8/site-packages/torch/include -I/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.8/site-packages/torch/include/TH -I/opt/conda/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/include/python3.8 -c -c /home/edwardhu/fastmoe/cuda/local_exchange.cu -o /home/edwardhu/fastmoe/build/temp.linux-x86_64-3.8/cuda/local_exchange.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DFMOE_USE_NCCL -DUSE_C10D_NCCL -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=fmoe_cuda -DTORCH_EXTENSION_NAME=fmoe_cuda -D_GLIBCXX_USE_CXX11_ABI=1 -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_52,code=sm_52 -gencode=arch=compute_86,code=sm_86 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_75,code=sm_75
[6/6] /usr/local/cuda/bin/nvcc -I/opt/conda/lib/python3.8/site-packages/torch/include -I/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.8/site-packages/torch/include/TH -I/opt/conda/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/include/python3.8 -c -c /home/edwardhu/fastmoe/cuda/balancing.cu -o /home/edwardhu/fastmoe/build/temp.linux-x86_64-3.8/cuda/balancing.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DFMOE_USE_NCCL -DUSE_C10D_NCCL -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=fmoe_cuda -DTORCH_EXTENSION_NAME=fmoe_cuda -D_GLIBCXX_USE_CXX11_ABI=1 -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_52,code=sm_52 -gencode=arch=compute_86,code=sm_86 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_75,code=sm_75
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1549, in _run_ninja_build
    subprocess.run(
  File "/opt/conda/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 38, in <module>
    setuptools.setup(
  File "/opt/conda/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/opt/conda/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/conda/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/conda/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/conda/lib/python3.8/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/opt/conda/lib/python3.8/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/opt/conda/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/conda/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/conda/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/opt/conda/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "/opt/conda/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/conda/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/conda/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/opt/conda/lib/python3.8/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/opt/conda/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/conda/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/conda/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/opt/conda/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/opt/conda/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 683, in build_extensions
    build_ext.build_extensions(self)
  File "/opt/conda/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 194, in build_extensions
    self.build_extension(ext)
  File "/opt/conda/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/opt/conda/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 503, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1261, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1565, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

**Platform (docker environment)**

The environment is unmodified image `nvcr.io/nvidia/pytorch:20.12-py3`. 

 - Device: [3 x NVIDIA V100 (16G)]
 - OS: [Ubuntu 20.04.1 LTS]
 - CUDA version: [11.3]
 - NCCL version: [2.8.3]
 - PyTorch version: [1.8.0a0+1606899]

**Additional context**
Building fastMoE under the [official pytorch container](https://hub.docker.com/r/pytorch/pytorch) with tag `1.9.1-cuda11.1-cudnn8-devel` seems fine. Not sure if earlier version PyTorch is deprecated or unsupported by fastMoE.

**Comment by BDHU** [comment]
A quick followup. The error message indicates line 118 in `cuda/global_exchange.cpp` yields this error. It seems that

```cpp
#if defined (TORCH_VERSION_MAJOR) **(TORCH_VERSION_MAJOR > 1) \\ ... 
```

is not detected despite my torch version meets the requirement. Commenting out the `#if` checking during compilation stage as well as `broadcastUniqueNCLLID(&ncclID);` seems to solve the problem. Not sure why for now.

**Comment by laekov** [comment]
The if macro you found was to deal with PyTorch's API variance between v1.7.x and v1.8.x.

As long as you are using PyTorch v1.8.0, you should have the macros defined, and go to the first branch. It is weird that in your compilation process, the compiler goes to the second branch that is used for v1.7.x and earilier versions. I suppose that the docker image is not using a proper release version of PyTorch.
