### ISSUE TITLE
ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by hanxuel** [laekov/fastmoe#97]
**Describe the bug**

**To Reproduce**
git clone https://github.com/laekov/fastmoe.git
cd fastmoe
git checkout 4edeccd95a66d1f2d5eb7ec7a9e40a9f67e0e393
psudo() { sudo env PATH="$PATH" "$@"; }
psudo python setup.py install

**Logs**
FAILED: /home/protago/hanxue/fastmoe/build/temp.linux-x86_64-3.6/cuda/fmoe_cuda.o
c++ -MMD -MF /home/protago/hanxue/fastmoe/build/temp.linux-x86_64-3.6/cuda/fmoe_cuda.o.d -pthread -B /home/protago/miniconda3/envs/moe/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/protago/miniconda3/envs/moe/lib/python3.6/site-packages/torch/include -I/home/protago/miniconda3/envs/moe/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/protago/miniconda3/envs/moe/lib/python3.6/site-packages/torch/include/TH -I/home/protago/miniconda3/envs/moe/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-11.1/include -I/home/protago/miniconda3/envs/moe/include/python3.6m -c -c /home/protago/hanxue/fastmoe/cuda/fmoe_cuda.cpp -o /home/protago/hanxue/fastmoe/build/temp.linux-x86_64-3.6/cuda/fmoe_cuda.o -DFMOE_USE_NCCL -DUSE_C10D_NCCL -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=fmoe_cuda -DTORCH_EXTENSION_NAME=fmoe_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/protago/miniconda3/envs/moe/lib/python3.6/site-packages/torch/include/ATen/Parallel.h:140,
                 from /home/protago/miniconda3/envs/moe/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                 from /home/protago/miniconda3/envs/moe/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                 from /home/protago/miniconda3/envs/moe/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                 from /home/protago/miniconda3/envs/moe/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/all.h:13,
                 from /home/protago/miniconda3/envs/moe/lib/python3.6/site-packages/torch/include/torch/extension.h:4,
                 from /home/protago/hanxue/fastmoe/cuda/fmoe_cuda.cpp:3:
/home/protago/miniconda3/envs/moe/lib/python3.6/site-packages/torch/include/ATen/ParallelOpenMP.h:83: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
   83 | #pragma omp parallel for if ((end - begin) >= grain_size)
      |
In file included from /home/protago/miniconda3/envs/moe/lib/python3.6/site-packages/torch/include/c10d/ProcessGroupNCCL.hpp:10,
                 from /home/protago/hanxue/fastmoe/cuda/fmoe_cuda.cpp:7:
/home/protago/miniconda3/envs/moe/lib/python3.6/site-packages/torch/include/c10d/NCCLUtils.hpp:9:10: fatal error: nccl.h: No such file or directory
    9 | #include <nccl.h>
      |          ^~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/protago/miniconda3/envs/moe/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1673, in _run_ninja_build
    env=env)
  File "/home/protago/miniconda3/envs/moe/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 67, in <module>
    'build_ext': BuildExtension
  File "/home/protago/miniconda3/envs/moe/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/protago/miniconda3/envs/moe/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/protago/miniconda3/envs/moe/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/protago/miniconda3/envs/moe/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/protago/miniconda3/envs/moe/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/protago/miniconda3/envs/moe/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/protago/miniconda3/envs/moe/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/protago/miniconda3/envs/moe/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/protago/miniconda3/envs/moe/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/protago/miniconda3/envs/moe/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/protago/miniconda3/envs/moe/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/protago/miniconda3/envs/moe/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/protago/miniconda3/envs/moe/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/protago/miniconda3/envs/moe/lib/python3.6/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/protago/miniconda3/envs/moe/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/protago/miniconda3/envs/moe/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/protago/miniconda3/envs/moe/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/protago/miniconda3/envs/moe/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/protago/miniconda3/envs/moe/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 708, in build_extensions
    build_ext.build_extensions(self)
  File "/home/protago/miniconda3/envs/moe/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/protago/miniconda3/envs/moe/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/protago/miniconda3/envs/moe/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/protago/miniconda3/envs/moe/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/protago/miniconda3/envs/moe/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 538, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/protago/miniconda3/envs/moe/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1359, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/protago/miniconda3/envs/moe/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1683, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Platform**
 - Device: [NVIDIA Driver Version: 470.103.01]
 - CUDA version: [11.1]
 - NCCL version: [2.7.8]
 - PyTorch version: [1.8.0]

**Comment by hanxuel** [comment]
Even though I try psudo USE_NCCL=1 python setup.py install
still meet the same error

**Comment by hanxuel** [comment]
I solved the problem via install nccl again following here:
https://docs.nvidia.com/deeplearning/nccl/install-guide/index.html
